site_name: Introduction to Discord for Beginners

nav:
  - Home: index.md
  - Set Up Your Server: instructionSet1.md
  - Start Activities with Friends: instructionSet2.md
  - Create Customized Stickers and Emojis: instructionSet3.md
  - Troubleshooting: Troubleshooting.md
  - Glossary: Glossary.md


theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - sane_lists